/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\laptop.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    laptop_base: THREE.Mesh
    screen: THREE.Mesh
  }
  materials: {}
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/laptop.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.laptop_base.geometry} material={nodes.laptop_base.material}>
        <mesh geometry={nodes.screen.geometry} material={nodes.screen.material} position={[0, 1.175, -1.266]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/laptop.glb')
