/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\phone.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    phone_base: THREE.Mesh
    phone_screen: THREE.Mesh
  }
  materials: {}
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/phone.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.phone_base.geometry} material={nodes.phone_base.material} />
      <mesh geometry={nodes.phone_screen.geometry} material={nodes.phone_screen.material} position={[0, 0.001, 0]} />
    </group>
  )
}

useGLTF.preload('/phone.glb')
