/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 .\public\models\vr_headset.glb -t 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    vr_visor: THREE.Mesh
    vr_visor_Screen: THREE.Mesh
  }
  materials: {}
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/vr_headset.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vr_visor.geometry} material={nodes.vr_visor.material}>
        <mesh geometry={nodes.vr_visor_Screen.geometry} material={nodes.vr_visor_Screen.material} position={[0, 0, 1.631]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/vr_headset.glb')
